###

http://localhost:3000

###
http://localhost:3000/api/v1/workouts

###
POST http://localhost:3000/api/v1/workouts

Content-Type: application/json
{
    "id": 5,
    "firstName": "Mark",
    "lastName": "Twain",
    "email": "mark@twain.com",
    "password": "password",
    "workout": "swam the gunk"
}
